from typing import Annotated
from langchain_core.tools import tool

@tool
def think(thought: str) -> str:
    """Use the tool to think about something.
This is perfect to start your workflow.
It will not obtain new information or take any actions, 
but just returns the thought generated and sent as input to this tool.
Use it when complex reasoning is needed.

:param thought: A thought to think about.
:return: New thought generated by you, which is under 30 words to keep the context window small."""
    return thought