import importlib
import inspect
from langchain_core.tools import tool


@tool
def think(thought: str) -> str:
    """Use the tool to think about something.
This is perfect to start your workflow.
It will not obtain new information or take any actions,
but just returns the thought generated and sent as input to this tool.
Use it when complex reasoning is needed.

:param thought: A thought to think about.
:return: New thought generated by you, which is under 30 words to keep the context window small."""
    return thought


@tool
def read_package_source(module_path: str) -> str:
    """Read the source code of any installed Python package module, class, or function.

Use this to understand how a library is implemented — e.g. to see how langgraph's
create_react_agent works, or inspect deepagents internals before using them.

Examples:
  module_path="langgraph.prebuilt.chat_agent_executor"  -> full module source
  module_path="langgraph.graph.state.StateGraph"         -> StateGraph class source
  module_path="deepagents.agent"                         -> full module source
  module_path="langchain_core.tools.base.BaseTool"       -> BaseTool class source

:param module_path: Dotted Python path to a module or a class/function within a module.
:return: Source code of the module or the specific symbol, or an error message.
"""
    try:
        parts = module_path.split(".")
        obj = None
        last_error = None

        # Try progressively shorter module paths to find the importable portion,
        # treating the remainder as attribute access (class/function).
        for split_at in range(len(parts), 0, -1):
            module_name = ".".join(parts[:split_at])
            attr_path = parts[split_at:]
            try:
                mod = importlib.import_module(module_name)
                obj = mod
                for attr in attr_path:
                    obj = getattr(obj, attr)
                break
            except (ImportError, AttributeError) as e:
                last_error = e
                continue

        if obj is None:
            return f"Could not import '{module_path}': {last_error}"

        if inspect.ismodule(obj):
            src_file = getattr(obj, "__file__", None)
            try:
                source = inspect.getsource(obj)
                return f"# Source: {src_file}\n\n{source}"
            except (OSError, TypeError):
                members = [n for n in dir(obj) if not n.startswith("_")]
                return f"# Module: {src_file}\n# Could not read full source. Public members:\n" + "\n".join(members)

        try:
            source = inspect.getsource(obj)
            src_file = inspect.getfile(obj)
            return f"# Source: {src_file}\n# {module_path}\n\n{source}"
        except (OSError, TypeError) as e:
            return f"Could not retrieve source for '{module_path}': {e}"

    except Exception as e:
        return f"Error: {e}"
